import Providers from '@/components/Providers';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark:bg-slate-900">
      <body className={inter.className}>
        <Providers>
          <div className="py-3">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
